# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
