# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20171016_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
