# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
